### ISSUE TITLE
Why not having And() and Or() functions?

### ISSUE THREAD

**Issue by semiversus** [smarie/python-mini-lambda#7]
As there is a ``Not`` function for ``not x`` operations it would be seems natural to have ``And`` and ``Or`` functions for logical operations. The documentation contains 

> the shortcircuit boolean operators and/or can not be overriden and check the return type, so you should use & or | instead

but this is not really true (or only true when you know what your doing). ``4 and 2`` evaluates to True but ``4 & 2`` evaluates to 0.

**Comment by semiversus** [comment]
`And` and `Or` can be replaced by the already existing `All` and `Any`... Drop the pull request (but maybe add as example additionally to `&` and `|`)

**Comment by smarie** [comment]
I agree that the current behaviour of mini-lambda bitwise operators & and | will sound counterintuitive to those who already know these operators in 'normal' python. Indeed in mini-lambda they **do not** behave like the normal bitwise & and |, but instead behave like `and` and `or`. See [here](https://github.com/smarie/python-mini-lambda/blob/master/mini_lambda/main.py#L112) for confirmation.

Maybe this was a bad choice ? I chose it because I thought that bitwise operations would be terribly rare in mini-lambda, while and and or would be very frequent.

So as a conclusion, what was really missing was BitwiseAnd and BitwiseOr :). But I accept the PR for consistency with `Not`, as you suggest.

**Comment by semiversus** [comment]
Ah, ok. I assumend bitwise logic for `&` and `|`. It's always a matter of application, but bitwise logic will be indeed a rare case.

**Comment by semiversus** [comment]
I'm always unsure who is in charge of closing an issue on github. The one bringing up the issue or the project maintainer. For me it's ok to close this issue.

**Comment by smarie** [comment]
For some unknown reason I did not get this notification :) 
Actually issues will close automatically if your git commit message says "Fixes #xx" so I almost never close issues by hand.
